### ISSUE TITLE
Cron not triggering syncing

### ISSUE THREAD

**Issue by LaikeSF** [kusold/todoist-habitrpg#39] opened 2015-12-20 11:57 UTC
I have followed the Cron Usage section and I can't seem to get this tool working. When I run the command directly, it has no problem running and returning a successful sync message, but when cron attempts to run the command, nothing happens. I've confirmed in the syslog that the following has run

Dec 20 04:40:01 ilp CRON[4074]: (laike) CMD (todoist-habitrpg -u ****-*****-*****-****-****** -t *******-****-****-****-******* -a ************ -f ~/HabitRPG)

but nothing is actually happening. I've censored out the API keys of course. I've tried to swap the command for a bash script to see if I can get it to return some error message or anything, but I can't seem to get anything back. I am stumped.

**Comment by kusold** [comment] 2015-12-20 15:06
Which operating system are you using? Also, can you please run `which node` and then also jump up to root and run `echo $PATH`





On Sun, Dec 20, 2015 at 3:57 AM -0800, "LaikeSF" <notifications@github.com> wrote:












I have followed the Cron Usage section and I can't seem to get this tool working I run the command directly, it has no problem running and returning a successful sync message, but when cron attempts to run the command, nothing happens I've confirmed in the syslog that the following has run



Dec 20 04:40:01 ilp CRON[4074]: (laike) CMD (todoist-habitrpg -u *----***** -t ****----****** -a ************ -f ~/HabitRPG)



but nothing is actually happening I've censored out the API keys of course I've tried to swap the command for a bash script to see if I can get it to return some error message or anything, but I can't seem to get anything back I am stumped

**Comment by LaikeSF** [comment] 2015-12-20 22:51
I'm running Ubuntu on a VPS. 

which node returns /usr/bin/node

echo $PATH returns /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

Thanks for the help.

**Comment by LaikeSF** [comment] 2015-12-23 08:21
Based on https://github.com/kusold/todoist-habitrpg/issues/20 I tried to adjust the command in cron to use the direct links (in my case, /usr/bin/node /usr/local/lib/node_modules/todoist-habitrpg/main.js). This seemed to have solved the problem. This might need to be added to the readme file.

**Comment by ricitron** [comment] 2016-09-01 19:10
Had this same issue, LikeSF your fix worked. Ubuntu 16.04.

**Comment by kusold** [comment] 2016-09-02 18:37
Awesome. Thanks for reporting. Closing the issue since this seems to be fixed.

**Closed by kusold** 2016-09-02 18:37 UTC
